# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from shared.proto import argos_pb2 as argos__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in argos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentC2Stub(object):
    """─────────────────────────── SERVICES ───────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/argos.AgentC2/Register',
                request_serializer=argos__pb2.AgentInfo.SerializeToString,
                response_deserializer=argos__pb2.RegisterAck.FromString,
                _registered_method=True)
        self.Beacon = channel.stream_stream(
                '/argos.AgentC2/Beacon',
                request_serializer=argos__pb2.AgentEvent.SerializeToString,
                response_deserializer=argos__pb2.DirectorCommand.FromString,
                _registered_method=True)
        self.ReportFinding = channel.unary_unary(
                '/argos.AgentC2/ReportFinding',
                request_serializer=argos__pb2.Finding.SerializeToString,
                response_deserializer=argos__pb2.FindingAck.FromString,
                _registered_method=True)


class AgentC2Servicer(object):
    """─────────────────────────── SERVICES ───────────────────────────

    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Beacon(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportFinding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentC2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=argos__pb2.AgentInfo.FromString,
                    response_serializer=argos__pb2.RegisterAck.SerializeToString,
            ),
            'Beacon': grpc.stream_stream_rpc_method_handler(
                    servicer.Beacon,
                    request_deserializer=argos__pb2.AgentEvent.FromString,
                    response_serializer=argos__pb2.DirectorCommand.SerializeToString,
            ),
            'ReportFinding': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportFinding,
                    request_deserializer=argos__pb2.Finding.FromString,
                    response_serializer=argos__pb2.FindingAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'argos.AgentC2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('argos.AgentC2', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentC2(object):
    """─────────────────────────── SERVICES ───────────────────────────

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.AgentC2/Register',
            argos__pb2.AgentInfo.SerializeToString,
            argos__pb2.RegisterAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Beacon(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/argos.AgentC2/Beacon',
            argos__pb2.AgentEvent.SerializeToString,
            argos__pb2.DirectorCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportFinding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.AgentC2/ReportFinding',
            argos__pb2.Finding.SerializeToString,
            argos__pb2.FindingAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OperatorConsoleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WatchMission = channel.unary_stream(
                '/argos.OperatorConsole/WatchMission',
                request_serializer=argos__pb2.MissionRequest.SerializeToString,
                response_deserializer=argos__pb2.MissionUpdate.FromString,
                _registered_method=True)
        self.ResolveDecision = channel.unary_unary(
                '/argos.OperatorConsole/ResolveDecision',
                request_serializer=argos__pb2.DecisionResponse.SerializeToString,
                response_deserializer=argos__pb2.DecisionAck.FromString,
                _registered_method=True)
        self.SetMode = channel.unary_unary(
                '/argos.OperatorConsole/SetMode',
                request_serializer=argos__pb2.ModeChange.SerializeToString,
                response_deserializer=argos__pb2.ModeAck.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/argos.OperatorConsole/ExecuteCommand',
                request_serializer=argos__pb2.ManualCommand.SerializeToString,
                response_deserializer=argos__pb2.CommandResult.FromString,
                _registered_method=True)
        self.GetWorldGraph = channel.unary_unary(
                '/argos.OperatorConsole/GetWorldGraph',
                request_serializer=argos__pb2.WorldGraphRequest.SerializeToString,
                response_deserializer=argos__pb2.WorldGraphSnapshot.FromString,
                _registered_method=True)


class OperatorConsoleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WatchMission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorldGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperatorConsoleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WatchMission': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchMission,
                    request_deserializer=argos__pb2.MissionRequest.FromString,
                    response_serializer=argos__pb2.MissionUpdate.SerializeToString,
            ),
            'ResolveDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveDecision,
                    request_deserializer=argos__pb2.DecisionResponse.FromString,
                    response_serializer=argos__pb2.DecisionAck.SerializeToString,
            ),
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=argos__pb2.ModeChange.FromString,
                    response_serializer=argos__pb2.ModeAck.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=argos__pb2.ManualCommand.FromString,
                    response_serializer=argos__pb2.CommandResult.SerializeToString,
            ),
            'GetWorldGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorldGraph,
                    request_deserializer=argos__pb2.WorldGraphRequest.FromString,
                    response_serializer=argos__pb2.WorldGraphSnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'argos.OperatorConsole', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('argos.OperatorConsole', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperatorConsole(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WatchMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/argos.OperatorConsole/WatchMission',
            argos__pb2.MissionRequest.SerializeToString,
            argos__pb2.MissionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.OperatorConsole/ResolveDecision',
            argos__pb2.DecisionResponse.SerializeToString,
            argos__pb2.DecisionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.OperatorConsole/SetMode',
            argos__pb2.ModeChange.SerializeToString,
            argos__pb2.ModeAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.OperatorConsole/ExecuteCommand',
            argos__pb2.ManualCommand.SerializeToString,
            argos__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorldGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.OperatorConsole/GetWorldGraph',
            argos__pb2.WorldGraphRequest.SerializeToString,
            argos__pb2.WorldGraphSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
