// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: argos.proto

package argospb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionProfile int32

const (
	ExecutionProfile_GHOST    ExecutionProfile = 0
	ExecutionProfile_BALANCED ExecutionProfile = 1
	ExecutionProfile_BLITZ    ExecutionProfile = 2
)

// Enum value maps for ExecutionProfile.
var (
	ExecutionProfile_name = map[int32]string{
		0: "GHOST",
		1: "BALANCED",
		2: "BLITZ",
	}
	ExecutionProfile_value = map[string]int32{
		"GHOST":    0,
		"BALANCED": 1,
		"BLITZ":    2,
	}
)

func (x ExecutionProfile) Enum() *ExecutionProfile {
	p := new(ExecutionProfile)
	*p = x
	return p
}

func (x ExecutionProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_argos_proto_enumTypes[0].Descriptor()
}

func (ExecutionProfile) Type() protoreflect.EnumType {
	return &file_argos_proto_enumTypes[0]
}

func (x ExecutionProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionProfile.Descriptor instead.
func (ExecutionProfile) EnumDescriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_HEARTBEAT        EventType = 0
	EventType_SCAN_RESULT      EventType = 1
	EventType_EXPLOIT_RESULT   EventType = 2
	EventType_CREDENTIAL_FOUND EventType = 3
	EventType_FLAG_CAPTURED    EventType = 4
	EventType_DEFENSE_ALERT    EventType = 5
	EventType_MODULE_LOADED    EventType = 6
	EventType_ERROR            EventType = 7
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "HEARTBEAT",
		1: "SCAN_RESULT",
		2: "EXPLOIT_RESULT",
		3: "CREDENTIAL_FOUND",
		4: "FLAG_CAPTURED",
		5: "DEFENSE_ALERT",
		6: "MODULE_LOADED",
		7: "ERROR",
	}
	EventType_value = map[string]int32{
		"HEARTBEAT":        0,
		"SCAN_RESULT":      1,
		"EXPLOIT_RESULT":   2,
		"CREDENTIAL_FOUND": 3,
		"FLAG_CAPTURED":    4,
		"DEFENSE_ALERT":    5,
		"MODULE_LOADED":    6,
		"ERROR":            7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_argos_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_argos_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{1}
}

type CommandType int32

const (
	CommandType_SCAN          CommandType = 0
	CommandType_EXPLOIT       CommandType = 1
	CommandType_PERSIST       CommandType = 2
	CommandType_EXFIL         CommandType = 3
	CommandType_PIVOT         CommandType = 4
	CommandType_CLEANUP       CommandType = 5
	CommandType_DEPLOY_MODULE CommandType = 6
	CommandType_SLEEP         CommandType = 7
	CommandType_SELF_DESTRUCT CommandType = 8
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "SCAN",
		1: "EXPLOIT",
		2: "PERSIST",
		3: "EXFIL",
		4: "PIVOT",
		5: "CLEANUP",
		6: "DEPLOY_MODULE",
		7: "SLEEP",
		8: "SELF_DESTRUCT",
	}
	CommandType_value = map[string]int32{
		"SCAN":          0,
		"EXPLOIT":       1,
		"PERSIST":       2,
		"EXFIL":         3,
		"PIVOT":         4,
		"CLEANUP":       5,
		"DEPLOY_MODULE": 6,
		"SLEEP":         7,
		"SELF_DESTRUCT": 8,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_argos_proto_enumTypes[2].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_argos_proto_enumTypes[2]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{2}
}

type FindingType int32

const (
	FindingType_HOST_DISCOVERED  FindingType = 0
	FindingType_SERVICE_OPEN     FindingType = 1
	FindingType_CREDENTIAL       FindingType = 2
	FindingType_VULNERABILITY    FindingType = 3
	FindingType_FLAG             FindingType = 4
	FindingType_DEFENSE_DETECTED FindingType = 5
)

// Enum value maps for FindingType.
var (
	FindingType_name = map[int32]string{
		0: "HOST_DISCOVERED",
		1: "SERVICE_OPEN",
		2: "CREDENTIAL",
		3: "VULNERABILITY",
		4: "FLAG",
		5: "DEFENSE_DETECTED",
	}
	FindingType_value = map[string]int32{
		"HOST_DISCOVERED":  0,
		"SERVICE_OPEN":     1,
		"CREDENTIAL":       2,
		"VULNERABILITY":    3,
		"FLAG":             4,
		"DEFENSE_DETECTED": 5,
	}
)

func (x FindingType) Enum() *FindingType {
	p := new(FindingType)
	*p = x
	return p
}

func (x FindingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingType) Descriptor() protoreflect.EnumDescriptor {
	return file_argos_proto_enumTypes[3].Descriptor()
}

func (FindingType) Type() protoreflect.EnumType {
	return &file_argos_proto_enumTypes[3]
}

func (x FindingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingType.Descriptor instead.
func (FindingType) EnumDescriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{3}
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	InternalIp    string                 `protobuf:"bytes,6,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	Processes     []string               `protobuf:"bytes,7,rep,name=processes,proto3" json:"processes,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,8,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       string                 `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_argos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AgentInfo) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *AgentInfo) GetProcesses() []string {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *AgentInfo) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RegisterAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BeaconIntervalSec uint32                 `protobuf:"varint,2,opt,name=beacon_interval_sec,json=beaconIntervalSec,proto3" json:"beacon_interval_sec,omitempty"`
	MissionId         string                 `protobuf:"bytes,3,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	DirectorVersion   string                 `protobuf:"bytes,4,opt,name=director_version,json=directorVersion,proto3" json:"director_version,omitempty"`
	Profile           ExecutionProfile       `protobuf:"varint,5,opt,name=profile,proto3,enum=argos.ExecutionProfile" json:"profile,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_argos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAck) GetBeaconIntervalSec() uint32 {
	if x != nil {
		return x.BeaconIntervalSec
	}
	return 0
}

func (x *RegisterAck) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *RegisterAck) GetDirectorVersion() string {
	if x != nil {
		return x.DirectorVersion
	}
	return ""
}

func (x *RegisterAck) GetProfile() ExecutionProfile {
	if x != nil {
		return x.Profile
	}
	return ExecutionProfile_GHOST
}

type AgentEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type      EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=argos.EventType" json:"type,omitempty"`
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*AgentEvent_Scan
	//	*AgentEvent_Exploit
	//	*AgentEvent_Cred
	//	*AgentEvent_Flag
	//	*AgentEvent_Defense
	//	*AgentEvent_Hb
	Event         isAgentEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_argos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{2}
}

func (x *AgentEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_HEARTBEAT
}

func (x *AgentEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentEvent) GetEvent() isAgentEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentEvent) GetScan() *ScanResult {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Scan); ok {
			return x.Scan
		}
	}
	return nil
}

func (x *AgentEvent) GetExploit() *ExploitResult {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Exploit); ok {
			return x.Exploit
		}
	}
	return nil
}

func (x *AgentEvent) GetCred() *CredentialFound {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Cred); ok {
			return x.Cred
		}
	}
	return nil
}

func (x *AgentEvent) GetFlag() *FlagCaptured {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Flag); ok {
			return x.Flag
		}
	}
	return nil
}

func (x *AgentEvent) GetDefense() *DefenseAlert {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Defense); ok {
			return x.Defense
		}
	}
	return nil
}

func (x *AgentEvent) GetHb() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Hb); ok {
			return x.Hb
		}
	}
	return nil
}

type isAgentEvent_Event interface {
	isAgentEvent_Event()
}

type AgentEvent_Scan struct {
	Scan *ScanResult `protobuf:"bytes,4,opt,name=scan,proto3,oneof"`
}

type AgentEvent_Exploit struct {
	Exploit *ExploitResult `protobuf:"bytes,5,opt,name=exploit,proto3,oneof"`
}

type AgentEvent_Cred struct {
	Cred *CredentialFound `protobuf:"bytes,6,opt,name=cred,proto3,oneof"`
}

type AgentEvent_Flag struct {
	Flag *FlagCaptured `protobuf:"bytes,7,opt,name=flag,proto3,oneof"`
}

type AgentEvent_Defense struct {
	Defense *DefenseAlert `protobuf:"bytes,8,opt,name=defense,proto3,oneof"`
}

type AgentEvent_Hb struct {
	Hb *Heartbeat `protobuf:"bytes,9,opt,name=hb,proto3,oneof"`
}

func (*AgentEvent_Scan) isAgentEvent_Event() {}

func (*AgentEvent_Exploit) isAgentEvent_Event() {}

func (*AgentEvent_Cred) isAgentEvent_Event() {}

func (*AgentEvent_Flag) isAgentEvent_Event() {}

func (*AgentEvent_Defense) isAgentEvent_Event() {}

func (*AgentEvent_Hb) isAgentEvent_Event() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemUsage      float32                `protobuf:"fixed32,2,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	IsElevated    bool                   `protobuf:"varint,3,opt,name=is_elevated,json=isElevated,proto3" json:"is_elevated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_argos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Heartbeat) GetMemUsage() float32 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *Heartbeat) GetIsElevated() bool {
	if x != nil {
		return x.IsElevated
	}
	return false
}

type ScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetIp      string                 `protobuf:"bytes,1,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	Services      []*ServiceInfo         `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	OsGuess       string                 `protobuf:"bytes,3,opt,name=os_guess,json=osGuess,proto3" json:"os_guess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResult) Reset() {
	*x = ScanResult{}
	mi := &file_argos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResult) ProtoMessage() {}

func (x *ScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResult.ProtoReflect.Descriptor instead.
func (*ScanResult) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{4}
}

func (x *ScanResult) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *ScanResult) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ScanResult) GetOsGuess() string {
	if x != nil {
		return x.OsGuess
	}
	return ""
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Banner        string                 `protobuf:"bytes,4,opt,name=banner,proto3" json:"banner,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Cpe           string                 `protobuf:"bytes,6,opt,name=cpe,proto3" json:"cpe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_argos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *ServiceInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInfo) GetCpe() string {
	if x != nil {
		return x.Cpe
	}
	return ""
}

type ExploitResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CveOrTechnique string                 `protobuf:"bytes,1,opt,name=cve_or_technique,json=cveOrTechnique,proto3" json:"cve_or_technique,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	SessionId      string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Output         string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExploitResult) Reset() {
	*x = ExploitResult{}
	mi := &file_argos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExploitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploitResult) ProtoMessage() {}

func (x *ExploitResult) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploitResult.ProtoReflect.Descriptor instead.
func (*ExploitResult) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{6}
}

func (x *ExploitResult) GetCveOrTechnique() string {
	if x != nil {
		return x.CveOrTechnique
	}
	return ""
}

func (x *ExploitResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExploitResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExploitResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExploitResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CredentialFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // password, ntlm_hash, kerberos_ticket, ssh_key
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"` // local, domain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialFound) Reset() {
	*x = CredentialFound{}
	mi := &file_argos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialFound) ProtoMessage() {}

func (x *CredentialFound) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialFound.ProtoReflect.Descriptor instead.
func (*CredentialFound) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{7}
}

func (x *CredentialFound) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CredentialFound) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CredentialFound) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CredentialFound) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CredentialFound) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type FlagCaptured struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	HostId        string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagCaptured) Reset() {
	*x = FlagCaptured{}
	mi := &file_argos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagCaptured) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagCaptured) ProtoMessage() {}

func (x *FlagCaptured) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagCaptured.ProtoReflect.Descriptor instead.
func (*FlagCaptured) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{8}
}

func (x *FlagCaptured) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FlagCaptured) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FlagCaptured) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type DefenseAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // edr, waf, honeypot, ids
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Severity      float32                `protobuf:"fixed32,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefenseAlert) Reset() {
	*x = DefenseAlert{}
	mi := &file_argos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefenseAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefenseAlert) ProtoMessage() {}

func (x *DefenseAlert) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefenseAlert.ProtoReflect.Descriptor instead.
func (*DefenseAlert) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{9}
}

func (x *DefenseAlert) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DefenseAlert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DefenseAlert) GetSeverity() float32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *DefenseAlert) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type DirectorCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type      CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=argos.CommandType" json:"type,omitempty"`
	Profile   ExecutionProfile       `protobuf:"varint,3,opt,name=profile,proto3,enum=argos.ExecutionProfile" json:"profile,omitempty"`
	TimeoutS  int32                  `protobuf:"varint,4,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DirectorCommand_ScanCmd
	//	*DirectorCommand_ExploitCmd
	//	*DirectorCommand_PersistCmd
	//	*DirectorCommand_ExfilCmd
	//	*DirectorCommand_PivotCmd
	//	*DirectorCommand_CleanupCmd
	//	*DirectorCommand_DeployCmd
	//	*DirectorCommand_SleepCmd
	Payload       isDirectorCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectorCommand) Reset() {
	*x = DirectorCommand{}
	mi := &file_argos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectorCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectorCommand) ProtoMessage() {}

func (x *DirectorCommand) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectorCommand.ProtoReflect.Descriptor instead.
func (*DirectorCommand) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{10}
}

func (x *DirectorCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *DirectorCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_SCAN
}

func (x *DirectorCommand) GetProfile() ExecutionProfile {
	if x != nil {
		return x.Profile
	}
	return ExecutionProfile_GHOST
}

func (x *DirectorCommand) GetTimeoutS() int32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

func (x *DirectorCommand) GetPayload() isDirectorCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DirectorCommand) GetScanCmd() *ScanCommand {
	if x != nil {
		if x, ok := x.Payload.(*DirectorCommand_ScanCmd); ok {
			return x.ScanCmd
		}
	}
	return nil
}

func (x *DirectorCommand) GetExploitCmd() *ExploitCommand {
	if x != nil {
		if x, ok := x.Payload.(*DirectorCommand_ExploitCmd); ok {
			return x.ExploitCmd
		}
	}
	return nil
}

func (x *DirectorCommand) GetPersistCmd() *PersistCommand {
	if x != nil {
		if x, ok := x.Payload.(*DirectorCommand_PersistCmd); ok {
			return x.PersistCmd
		}
	}
	return nil
}

func (x *DirectorCommand) GetExfilCmd() *ExfilCommand {
	if x != nil {
		if x, ok := x.Payload.(*DirectorCommand_ExfilCmd); ok {
			return x.ExfilCmd
		}
	}
	return nil
}

func (x *DirectorCommand) GetPivotCmd() *PivotCommand {
	if x != nil {
		if x, ok := x.Payload.(*DirectorCommand_PivotCmd); ok {
			return x.PivotCmd
		}
	}
	return nil
}

func (x *DirectorCommand) GetCleanupCmd() *CleanupCommand {
	if x != nil {
		if x, ok := x.Payload.(*DirectorCommand_CleanupCmd); ok {
			return x.CleanupCmd
		}
	}
	return nil
}

func (x *DirectorCommand) GetDeployCmd() *DeployCommand {
	if x != nil {
		if x, ok := x.Payload.(*DirectorCommand_DeployCmd); ok {
			return x.DeployCmd
		}
	}
	return nil
}

func (x *DirectorCommand) GetSleepCmd() *SleepCommand {
	if x != nil {
		if x, ok := x.Payload.(*DirectorCommand_SleepCmd); ok {
			return x.SleepCmd
		}
	}
	return nil
}

type isDirectorCommand_Payload interface {
	isDirectorCommand_Payload()
}

type DirectorCommand_ScanCmd struct {
	ScanCmd *ScanCommand `protobuf:"bytes,5,opt,name=scan_cmd,json=scanCmd,proto3,oneof"`
}

type DirectorCommand_ExploitCmd struct {
	ExploitCmd *ExploitCommand `protobuf:"bytes,6,opt,name=exploit_cmd,json=exploitCmd,proto3,oneof"`
}

type DirectorCommand_PersistCmd struct {
	PersistCmd *PersistCommand `protobuf:"bytes,7,opt,name=persist_cmd,json=persistCmd,proto3,oneof"`
}

type DirectorCommand_ExfilCmd struct {
	ExfilCmd *ExfilCommand `protobuf:"bytes,8,opt,name=exfil_cmd,json=exfilCmd,proto3,oneof"`
}

type DirectorCommand_PivotCmd struct {
	PivotCmd *PivotCommand `protobuf:"bytes,9,opt,name=pivot_cmd,json=pivotCmd,proto3,oneof"`
}

type DirectorCommand_CleanupCmd struct {
	CleanupCmd *CleanupCommand `protobuf:"bytes,10,opt,name=cleanup_cmd,json=cleanupCmd,proto3,oneof"`
}

type DirectorCommand_DeployCmd struct {
	DeployCmd *DeployCommand `protobuf:"bytes,11,opt,name=deploy_cmd,json=deployCmd,proto3,oneof"`
}

type DirectorCommand_SleepCmd struct {
	SleepCmd *SleepCommand `protobuf:"bytes,12,opt,name=sleep_cmd,json=sleepCmd,proto3,oneof"`
}

func (*DirectorCommand_ScanCmd) isDirectorCommand_Payload() {}

func (*DirectorCommand_ExploitCmd) isDirectorCommand_Payload() {}

func (*DirectorCommand_PersistCmd) isDirectorCommand_Payload() {}

func (*DirectorCommand_ExfilCmd) isDirectorCommand_Payload() {}

func (*DirectorCommand_PivotCmd) isDirectorCommand_Payload() {}

func (*DirectorCommand_CleanupCmd) isDirectorCommand_Payload() {}

func (*DirectorCommand_DeployCmd) isDirectorCommand_Payload() {}

func (*DirectorCommand_SleepCmd) isDirectorCommand_Payload() {}

type ScanCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []string               `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	ScanType      string                 `protobuf:"bytes,2,opt,name=scan_type,json=scanType,proto3" json:"scan_type,omitempty"` // tcp_syn, http_banner, smb, ldap, udp
	Rate          int32                  `protobuf:"varint,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Ports         []uint32               `protobuf:"varint,4,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanCommand) Reset() {
	*x = ScanCommand{}
	mi := &file_argos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanCommand) ProtoMessage() {}

func (x *ScanCommand) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanCommand.ProtoReflect.Descriptor instead.
func (*ScanCommand) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{11}
}

func (x *ScanCommand) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ScanCommand) GetScanType() string {
	if x != nil {
		return x.ScanType
	}
	return ""
}

func (x *ScanCommand) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ScanCommand) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type ExploitCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetHost    string                 `protobuf:"bytes,1,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort    uint32                 `protobuf:"varint,2,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Technique     string                 `protobuf:"bytes,3,opt,name=technique,proto3" json:"technique,omitempty"`
	Cve           string                 `protobuf:"bytes,4,opt,name=cve,proto3" json:"cve,omitempty"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExploitCommand) Reset() {
	*x = ExploitCommand{}
	mi := &file_argos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExploitCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploitCommand) ProtoMessage() {}

func (x *ExploitCommand) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploitCommand.ProtoReflect.Descriptor instead.
func (*ExploitCommand) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{12}
}

func (x *ExploitCommand) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *ExploitCommand) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *ExploitCommand) GetTechnique() string {
	if x != nil {
		return x.Technique
	}
	return ""
}

func (x *ExploitCommand) GetCve() string {
	if x != nil {
		return x.Cve
	}
	return ""
}

func (x *ExploitCommand) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type PersistCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"` // com_hijack, wmi, registry, cron, systemd
	PayloadPath   string                 `protobuf:"bytes,2,opt,name=payload_path,json=payloadPath,proto3" json:"payload_path,omitempty"`
	Elevate       bool                   `protobuf:"varint,3,opt,name=elevate,proto3" json:"elevate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistCommand) Reset() {
	*x = PersistCommand{}
	mi := &file_argos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistCommand) ProtoMessage() {}

func (x *PersistCommand) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistCommand.ProtoReflect.Descriptor instead.
func (*PersistCommand) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{13}
}

func (x *PersistCommand) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PersistCommand) GetPayloadPath() string {
	if x != nil {
		return x.PayloadPath
	}
	return ""
}

func (x *PersistCommand) GetElevate() bool {
	if x != nil {
		return x.Elevate
	}
	return false
}

type ExfilCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	C2Endpoint    string                 `protobuf:"bytes,2,opt,name=c2_endpoint,json=c2Endpoint,proto3" json:"c2_endpoint,omitempty"`
	Encrypt       bool                   `protobuf:"varint,3,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExfilCommand) Reset() {
	*x = ExfilCommand{}
	mi := &file_argos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExfilCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExfilCommand) ProtoMessage() {}

func (x *ExfilCommand) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExfilCommand.ProtoReflect.Descriptor instead.
func (*ExfilCommand) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{14}
}

func (x *ExfilCommand) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *ExfilCommand) GetC2Endpoint() string {
	if x != nil {
		return x.C2Endpoint
	}
	return ""
}

func (x *ExfilCommand) GetEncrypt() bool {
	if x != nil {
		return x.Encrypt
	}
	return false
}

type PivotCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNetwork string                 `protobuf:"bytes,1,opt,name=target_network,json=targetNetwork,proto3" json:"target_network,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // socks5, ssh_tunnel, smb
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PivotCommand) Reset() {
	*x = PivotCommand{}
	mi := &file_argos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PivotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PivotCommand) ProtoMessage() {}

func (x *PivotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PivotCommand.ProtoReflect.Descriptor instead.
func (*PivotCommand) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{15}
}

func (x *PivotCommand) GetTargetNetwork() string {
	if x != nil {
		return x.TargetNetwork
	}
	return ""
}

func (x *PivotCommand) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type CleanupCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RemovePersistence bool                   `protobuf:"varint,1,opt,name=remove_persistence,json=removePersistence,proto3" json:"remove_persistence,omitempty"`
	ClearLogs         bool                   `protobuf:"varint,2,opt,name=clear_logs,json=clearLogs,proto3" json:"clear_logs,omitempty"`
	SelfDelete        bool                   `protobuf:"varint,3,opt,name=self_delete,json=selfDelete,proto3" json:"self_delete,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CleanupCommand) Reset() {
	*x = CleanupCommand{}
	mi := &file_argos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupCommand) ProtoMessage() {}

func (x *CleanupCommand) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupCommand.ProtoReflect.Descriptor instead.
func (*CleanupCommand) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{16}
}

func (x *CleanupCommand) GetRemovePersistence() bool {
	if x != nil {
		return x.RemovePersistence
	}
	return false
}

func (x *CleanupCommand) GetClearLogs() bool {
	if x != nil {
		return x.ClearLogs
	}
	return false
}

func (x *CleanupCommand) GetSelfDelete() bool {
	if x != nil {
		return x.SelfDelete
	}
	return false
}

type DeployCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleName    string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	ModuleData    []byte                 `protobuf:"bytes,2,opt,name=module_data,json=moduleData,proto3" json:"module_data,omitempty"` // binario en memoria
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployCommand) Reset() {
	*x = DeployCommand{}
	mi := &file_argos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployCommand) ProtoMessage() {}

func (x *DeployCommand) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployCommand.ProtoReflect.Descriptor instead.
func (*DeployCommand) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{17}
}

func (x *DeployCommand) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *DeployCommand) GetModuleData() []byte {
	if x != nil {
		return x.ModuleData
	}
	return nil
}

func (x *DeployCommand) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type SleepCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationSec   uint32                 `protobuf:"varint,1,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	Jitter        bool                   `protobuf:"varint,2,opt,name=jitter,proto3" json:"jitter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepCommand) Reset() {
	*x = SleepCommand{}
	mi := &file_argos_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepCommand) ProtoMessage() {}

func (x *SleepCommand) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepCommand.ProtoReflect.Descriptor instead.
func (*SleepCommand) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{18}
}

func (x *SleepCommand) GetDurationSec() uint32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *SleepCommand) GetJitter() bool {
	if x != nil {
		return x.Jitter
	}
	return false
}

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type          FindingType            `protobuf:"varint,2,opt,name=type,proto3,enum=argos.FindingType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Evidence      []byte                 `protobuf:"bytes,4,opt,name=evidence,proto3" json:"evidence,omitempty"`
	FlagValue     string                 `protobuf:"bytes,5,opt,name=flag_value,json=flagValue,proto3" json:"flag_value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_argos_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{19}
}

func (x *Finding) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Finding) GetType() FindingType {
	if x != nil {
		return x.Type
	}
	return FindingType_HOST_DISCOVERED
}

func (x *Finding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Finding) GetEvidence() []byte {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Finding) GetFlagValue() string {
	if x != nil {
		return x.FlagValue
	}
	return ""
}

func (x *Finding) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type FindingAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingAck) Reset() {
	*x = FindingAck{}
	mi := &file_argos_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingAck) ProtoMessage() {}

func (x *FindingAck) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingAck.ProtoReflect.Descriptor instead.
func (*FindingAck) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{20}
}

func (x *FindingAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *FindingAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type MissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     string                 `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionRequest) Reset() {
	*x = MissionRequest{}
	mi := &file_argos_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionRequest) ProtoMessage() {}

func (x *MissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionRequest.ProtoReflect.Descriptor instead.
func (*MissionRequest) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{21}
}

func (x *MissionRequest) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

type MissionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON serializado del evento
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionUpdate) Reset() {
	*x = MissionUpdate{}
	mi := &file_argos_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionUpdate) ProtoMessage() {}

func (x *MissionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionUpdate.ProtoReflect.Descriptor instead.
func (*MissionUpdate) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{22}
}

func (x *MissionUpdate) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MissionUpdate) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *MissionUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	CustomCmd     string                 `protobuf:"bytes,3,opt,name=custom_cmd,json=customCmd,proto3" json:"custom_cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_argos_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{23}
}

func (x *DecisionResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *DecisionResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *DecisionResponse) GetCustomCmd() string {
	if x != nil {
		return x.CustomCmd
	}
	return ""
}

type DecisionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionAck) Reset() {
	*x = DecisionAck{}
	mi := &file_argos_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionAck) ProtoMessage() {}

func (x *DecisionAck) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionAck.ProtoReflect.Descriptor instead.
func (*DecisionAck) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{24}
}

func (x *DecisionAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DecisionAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ModeChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       ExecutionProfile       `protobuf:"varint,1,opt,name=profile,proto3,enum=argos.ExecutionProfile" json:"profile,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // pentest | ctf
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeChange) Reset() {
	*x = ModeChange{}
	mi := &file_argos_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeChange) ProtoMessage() {}

func (x *ModeChange) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeChange.ProtoReflect.Descriptor instead.
func (*ModeChange) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{25}
}

func (x *ModeChange) GetProfile() ExecutionProfile {
	if x != nil {
		return x.Profile
	}
	return ExecutionProfile_GHOST
}

func (x *ModeChange) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ModeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeAck) Reset() {
	*x = ModeAck{}
	mi := &file_argos_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeAck) ProtoMessage() {}

func (x *ModeAck) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeAck.ProtoReflect.Descriptor instead.
func (*ModeAck) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{26}
}

func (x *ModeAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ManualCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualCommand) Reset() {
	*x = ManualCommand{}
	mi := &file_argos_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualCommand) ProtoMessage() {}

func (x *ManualCommand) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualCommand.ProtoReflect.Descriptor instead.
func (*ManualCommand) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{27}
}

func (x *ManualCommand) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ManualCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_argos_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{28}
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type WorldGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldGraphRequest) Reset() {
	*x = WorldGraphRequest{}
	mi := &file_argos_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldGraphRequest) ProtoMessage() {}

func (x *WorldGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldGraphRequest.ProtoReflect.Descriptor instead.
func (*WorldGraphRequest) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{29}
}

type WorldGraphSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraphJson     string                 `protobuf:"bytes,1,opt,name=graph_json,json=graphJson,proto3" json:"graph_json,omitempty"` // JSON serializado del grafo NetworkX
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldGraphSnapshot) Reset() {
	*x = WorldGraphSnapshot{}
	mi := &file_argos_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldGraphSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldGraphSnapshot) ProtoMessage() {}

func (x *WorldGraphSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_argos_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldGraphSnapshot.ProtoReflect.Descriptor instead.
func (*WorldGraphSnapshot) Descriptor() ([]byte, []int) {
	return file_argos_proto_rawDescGZIP(), []int{30}
}

func (x *WorldGraphSnapshot) GetGraphJson() string {
	if x != nil {
		return x.GraphJson
	}
	return ""
}

func (x *WorldGraphSnapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_argos_proto protoreflect.FileDescriptor

const file_argos_proto_rawDesc = "" +
	"\n" +
	"\vargos.proto\x12\x05argos\"\xd6\x02\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x1f\n" +
	"\vinternal_ip\x18\x06 \x01(\tR\n" +
	"internalIp\x12\x1c\n" +
	"\tprocesses\x18\a \x03(\tR\tprocesses\x12.\n" +
	"\x04meta\x18\b \x03(\v2\x1a.argos.AgentInfo.MetaEntryR\x04meta\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\vRegisterAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x13beacon_interval_sec\x18\x02 \x01(\rR\x11beaconIntervalSec\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x03 \x01(\tR\tmissionId\x12)\n" +
	"\x10director_version\x18\x04 \x01(\tR\x0fdirectorVersion\x121\n" +
	"\aprofile\x18\x05 \x01(\x0e2\x17.argos.ExecutionProfileR\aprofile\"\xfd\x02\n" +
	"\n" +
	"AgentEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12$\n" +
	"\x04type\x18\x02 \x01(\x0e2\x10.argos.EventTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12'\n" +
	"\x04scan\x18\x04 \x01(\v2\x11.argos.ScanResultH\x00R\x04scan\x120\n" +
	"\aexploit\x18\x05 \x01(\v2\x14.argos.ExploitResultH\x00R\aexploit\x12,\n" +
	"\x04cred\x18\x06 \x01(\v2\x16.argos.CredentialFoundH\x00R\x04cred\x12)\n" +
	"\x04flag\x18\a \x01(\v2\x13.argos.FlagCapturedH\x00R\x04flag\x12/\n" +
	"\adefense\x18\b \x01(\v2\x13.argos.DefenseAlertH\x00R\adefense\x12\"\n" +
	"\x02hb\x18\t \x01(\v2\x10.argos.HeartbeatH\x00R\x02hbB\a\n" +
	"\x05event\"f\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tmem_usage\x18\x02 \x01(\x02R\bmemUsage\x12\x1f\n" +
	"\vis_elevated\x18\x03 \x01(\bR\n" +
	"isElevated\"t\n" +
	"\n" +
	"ScanResult\x12\x1b\n" +
	"\ttarget_ip\x18\x01 \x01(\tR\btargetIp\x12.\n" +
	"\bservices\x18\x02 \x03(\v2\x12.argos.ServiceInfoR\bservices\x12\x19\n" +
	"\bos_guess\x18\x03 \x01(\tR\aosGuess\"\x95\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06banner\x18\x04 \x01(\tR\x06banner\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x10\n" +
	"\x03cpe\x18\x06 \x01(\tR\x03cpe\"\xa0\x01\n" +
	"\rExploitResult\x12(\n" +
	"\x10cve_or_technique\x18\x01 \x01(\tR\x0ecveOrTechnique\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x85\x01\n" +
	"\x0fCredentialFound\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\"Q\n" +
	"\fFlagCaptured\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\"j\n" +
	"\fDefenseAlert\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\x02R\bseverity\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\xe5\x04\n" +
	"\x0fDirectorCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.argos.CommandTypeR\x04type\x121\n" +
	"\aprofile\x18\x03 \x01(\x0e2\x17.argos.ExecutionProfileR\aprofile\x12\x1b\n" +
	"\ttimeout_s\x18\x04 \x01(\x05R\btimeoutS\x12/\n" +
	"\bscan_cmd\x18\x05 \x01(\v2\x12.argos.ScanCommandH\x00R\ascanCmd\x128\n" +
	"\vexploit_cmd\x18\x06 \x01(\v2\x15.argos.ExploitCommandH\x00R\n" +
	"exploitCmd\x128\n" +
	"\vpersist_cmd\x18\a \x01(\v2\x15.argos.PersistCommandH\x00R\n" +
	"persistCmd\x122\n" +
	"\texfil_cmd\x18\b \x01(\v2\x13.argos.ExfilCommandH\x00R\bexfilCmd\x122\n" +
	"\tpivot_cmd\x18\t \x01(\v2\x13.argos.PivotCommandH\x00R\bpivotCmd\x128\n" +
	"\vcleanup_cmd\x18\n" +
	" \x01(\v2\x15.argos.CleanupCommandH\x00R\n" +
	"cleanupCmd\x125\n" +
	"\n" +
	"deploy_cmd\x18\v \x01(\v2\x14.argos.DeployCommandH\x00R\tdeployCmd\x122\n" +
	"\tsleep_cmd\x18\f \x01(\v2\x13.argos.SleepCommandH\x00R\bsleepCmdB\t\n" +
	"\apayload\"n\n" +
	"\vScanCommand\x12\x18\n" +
	"\atargets\x18\x01 \x03(\tR\atargets\x12\x1b\n" +
	"\tscan_type\x18\x02 \x01(\tR\bscanType\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x05R\x04rate\x12\x14\n" +
	"\x05ports\x18\x04 \x03(\rR\x05ports\"\xf8\x01\n" +
	"\x0eExploitCommand\x12\x1f\n" +
	"\vtarget_host\x18\x01 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x02 \x01(\rR\n" +
	"targetPort\x12\x1c\n" +
	"\ttechnique\x18\x03 \x01(\tR\ttechnique\x12\x10\n" +
	"\x03cve\x18\x04 \x01(\tR\x03cve\x129\n" +
	"\x06params\x18\x05 \x03(\v2!.argos.ExploitCommand.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x0ePersistCommand\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12!\n" +
	"\fpayload_path\x18\x02 \x01(\tR\vpayloadPath\x12\x18\n" +
	"\aelevate\x18\x03 \x01(\bR\aelevate\"_\n" +
	"\fExfilCommand\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12\x1f\n" +
	"\vc2_endpoint\x18\x02 \x01(\tR\n" +
	"c2Endpoint\x12\x18\n" +
	"\aencrypt\x18\x03 \x01(\bR\aencrypt\"M\n" +
	"\fPivotCommand\x12%\n" +
	"\x0etarget_network\x18\x01 \x01(\tR\rtargetNetwork\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"\x7f\n" +
	"\x0eCleanupCommand\x12-\n" +
	"\x12remove_persistence\x18\x01 \x01(\bR\x11removePersistence\x12\x1d\n" +
	"\n" +
	"clear_logs\x18\x02 \x01(\bR\tclearLogs\x12\x1f\n" +
	"\vself_delete\x18\x03 \x01(\bR\n" +
	"selfDelete\"\xc6\x01\n" +
	"\rDeployCommand\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\x12\x1f\n" +
	"\vmodule_data\x18\x02 \x01(\fR\n" +
	"moduleData\x128\n" +
	"\x06params\x18\x03 \x03(\v2 .argos.DeployCommand.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\fSleepCommand\x12!\n" +
	"\fduration_sec\x18\x01 \x01(\rR\vdurationSec\x12\x16\n" +
	"\x06jitter\x18\x02 \x01(\bR\x06jitter\"\xc7\x01\n" +
	"\aFinding\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.argos.FindingTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bevidence\x18\x04 \x01(\fR\bevidence\x12\x1d\n" +
	"\n" +
	"flag_value\x18\x05 \x01(\tR\tflagValue\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"A\n" +
	"\n" +
	"FindingAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"/\n" +
	"\x0eMissionRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\tR\tmissionId\"f\n" +
	"\rMissionUpdate\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"n\n" +
	"\x10DecisionResponse\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x1d\n" +
	"\n" +
	"custom_cmd\x18\x03 \x01(\tR\tcustomCmd\"7\n" +
	"\vDecisionAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\n" +
	"ModeChange\x121\n" +
	"\aprofile\x18\x01 \x01(\x0e2\x17.argos.ExecutionProfileR\aprofile\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"\x19\n" +
	"\aModeAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"D\n" +
	"\rManualCommand\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"M\n" +
	"\rCommandResult\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\"\x13\n" +
	"\x11WorldGraphRequest\"Q\n" +
	"\x12WorldGraphSnapshot\x12\x1d\n" +
	"\n" +
	"graph_json\x18\x01 \x01(\tR\tgraphJson\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp*6\n" +
	"\x10ExecutionProfile\x12\t\n" +
	"\x05GHOST\x10\x00\x12\f\n" +
	"\bBALANCED\x10\x01\x12\t\n" +
	"\x05BLITZ\x10\x02*\x99\x01\n" +
	"\tEventType\x12\r\n" +
	"\tHEARTBEAT\x10\x00\x12\x0f\n" +
	"\vSCAN_RESULT\x10\x01\x12\x12\n" +
	"\x0eEXPLOIT_RESULT\x10\x02\x12\x14\n" +
	"\x10CREDENTIAL_FOUND\x10\x03\x12\x11\n" +
	"\rFLAG_CAPTURED\x10\x04\x12\x11\n" +
	"\rDEFENSE_ALERT\x10\x05\x12\x11\n" +
	"\rMODULE_LOADED\x10\x06\x12\t\n" +
	"\x05ERROR\x10\a*\x85\x01\n" +
	"\vCommandType\x12\b\n" +
	"\x04SCAN\x10\x00\x12\v\n" +
	"\aEXPLOIT\x10\x01\x12\v\n" +
	"\aPERSIST\x10\x02\x12\t\n" +
	"\x05EXFIL\x10\x03\x12\t\n" +
	"\x05PIVOT\x10\x04\x12\v\n" +
	"\aCLEANUP\x10\x05\x12\x11\n" +
	"\rDEPLOY_MODULE\x10\x06\x12\t\n" +
	"\x05SLEEP\x10\a\x12\x11\n" +
	"\rSELF_DESTRUCT\x10\b*w\n" +
	"\vFindingType\x12\x13\n" +
	"\x0fHOST_DISCOVERED\x10\x00\x12\x10\n" +
	"\fSERVICE_OPEN\x10\x01\x12\x0e\n" +
	"\n" +
	"CREDENTIAL\x10\x02\x12\x11\n" +
	"\rVULNERABILITY\x10\x03\x12\b\n" +
	"\x04FLAG\x10\x04\x12\x14\n" +
	"\x10DEFENSE_DETECTED\x10\x052\xa8\x01\n" +
	"\aAgentC2\x120\n" +
	"\bRegister\x12\x10.argos.AgentInfo\x1a\x12.argos.RegisterAck\x127\n" +
	"\x06Beacon\x12\x11.argos.AgentEvent\x1a\x16.argos.DirectorCommand(\x010\x01\x122\n" +
	"\rReportFinding\x12\x0e.argos.Finding\x1a\x11.argos.FindingAck2\xc2\x02\n" +
	"\x0fOperatorConsole\x12=\n" +
	"\fWatchMission\x12\x15.argos.MissionRequest\x1a\x14.argos.MissionUpdate0\x01\x12>\n" +
	"\x0fResolveDecision\x12\x17.argos.DecisionResponse\x1a\x12.argos.DecisionAck\x12,\n" +
	"\aSetMode\x12\x11.argos.ModeChange\x1a\x0e.argos.ModeAck\x12<\n" +
	"\x0eExecuteCommand\x12\x14.argos.ManualCommand\x1a\x14.argos.CommandResult\x12D\n" +
	"\rGetWorldGraph\x12\x18.argos.WorldGraphRequest\x1a\x19.argos.WorldGraphSnapshotB'Z%github.com/argos/shared/proto;argospbb\x06proto3"

var (
	file_argos_proto_rawDescOnce sync.Once
	file_argos_proto_rawDescData []byte
)

func file_argos_proto_rawDescGZIP() []byte {
	file_argos_proto_rawDescOnce.Do(func() {
		file_argos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argos_proto_rawDesc), len(file_argos_proto_rawDesc)))
	})
	return file_argos_proto_rawDescData
}

var file_argos_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_argos_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_argos_proto_goTypes = []any{
	(ExecutionProfile)(0),      // 0: argos.ExecutionProfile
	(EventType)(0),             // 1: argos.EventType
	(CommandType)(0),           // 2: argos.CommandType
	(FindingType)(0),           // 3: argos.FindingType
	(*AgentInfo)(nil),          // 4: argos.AgentInfo
	(*RegisterAck)(nil),        // 5: argos.RegisterAck
	(*AgentEvent)(nil),         // 6: argos.AgentEvent
	(*Heartbeat)(nil),          // 7: argos.Heartbeat
	(*ScanResult)(nil),         // 8: argos.ScanResult
	(*ServiceInfo)(nil),        // 9: argos.ServiceInfo
	(*ExploitResult)(nil),      // 10: argos.ExploitResult
	(*CredentialFound)(nil),    // 11: argos.CredentialFound
	(*FlagCaptured)(nil),       // 12: argos.FlagCaptured
	(*DefenseAlert)(nil),       // 13: argos.DefenseAlert
	(*DirectorCommand)(nil),    // 14: argos.DirectorCommand
	(*ScanCommand)(nil),        // 15: argos.ScanCommand
	(*ExploitCommand)(nil),     // 16: argos.ExploitCommand
	(*PersistCommand)(nil),     // 17: argos.PersistCommand
	(*ExfilCommand)(nil),       // 18: argos.ExfilCommand
	(*PivotCommand)(nil),       // 19: argos.PivotCommand
	(*CleanupCommand)(nil),     // 20: argos.CleanupCommand
	(*DeployCommand)(nil),      // 21: argos.DeployCommand
	(*SleepCommand)(nil),       // 22: argos.SleepCommand
	(*Finding)(nil),            // 23: argos.Finding
	(*FindingAck)(nil),         // 24: argos.FindingAck
	(*MissionRequest)(nil),     // 25: argos.MissionRequest
	(*MissionUpdate)(nil),      // 26: argos.MissionUpdate
	(*DecisionResponse)(nil),   // 27: argos.DecisionResponse
	(*DecisionAck)(nil),        // 28: argos.DecisionAck
	(*ModeChange)(nil),         // 29: argos.ModeChange
	(*ModeAck)(nil),            // 30: argos.ModeAck
	(*ManualCommand)(nil),      // 31: argos.ManualCommand
	(*CommandResult)(nil),      // 32: argos.CommandResult
	(*WorldGraphRequest)(nil),  // 33: argos.WorldGraphRequest
	(*WorldGraphSnapshot)(nil), // 34: argos.WorldGraphSnapshot
	nil,                        // 35: argos.AgentInfo.MetaEntry
	nil,                        // 36: argos.ExploitCommand.ParamsEntry
	nil,                        // 37: argos.DeployCommand.ParamsEntry
}
var file_argos_proto_depIdxs = []int32{
	35, // 0: argos.AgentInfo.meta:type_name -> argos.AgentInfo.MetaEntry
	0,  // 1: argos.RegisterAck.profile:type_name -> argos.ExecutionProfile
	1,  // 2: argos.AgentEvent.type:type_name -> argos.EventType
	8,  // 3: argos.AgentEvent.scan:type_name -> argos.ScanResult
	10, // 4: argos.AgentEvent.exploit:type_name -> argos.ExploitResult
	11, // 5: argos.AgentEvent.cred:type_name -> argos.CredentialFound
	12, // 6: argos.AgentEvent.flag:type_name -> argos.FlagCaptured
	13, // 7: argos.AgentEvent.defense:type_name -> argos.DefenseAlert
	7,  // 8: argos.AgentEvent.hb:type_name -> argos.Heartbeat
	9,  // 9: argos.ScanResult.services:type_name -> argos.ServiceInfo
	2,  // 10: argos.DirectorCommand.type:type_name -> argos.CommandType
	0,  // 11: argos.DirectorCommand.profile:type_name -> argos.ExecutionProfile
	15, // 12: argos.DirectorCommand.scan_cmd:type_name -> argos.ScanCommand
	16, // 13: argos.DirectorCommand.exploit_cmd:type_name -> argos.ExploitCommand
	17, // 14: argos.DirectorCommand.persist_cmd:type_name -> argos.PersistCommand
	18, // 15: argos.DirectorCommand.exfil_cmd:type_name -> argos.ExfilCommand
	19, // 16: argos.DirectorCommand.pivot_cmd:type_name -> argos.PivotCommand
	20, // 17: argos.DirectorCommand.cleanup_cmd:type_name -> argos.CleanupCommand
	21, // 18: argos.DirectorCommand.deploy_cmd:type_name -> argos.DeployCommand
	22, // 19: argos.DirectorCommand.sleep_cmd:type_name -> argos.SleepCommand
	36, // 20: argos.ExploitCommand.params:type_name -> argos.ExploitCommand.ParamsEntry
	37, // 21: argos.DeployCommand.params:type_name -> argos.DeployCommand.ParamsEntry
	3,  // 22: argos.Finding.type:type_name -> argos.FindingType
	0,  // 23: argos.ModeChange.profile:type_name -> argos.ExecutionProfile
	4,  // 24: argos.AgentC2.Register:input_type -> argos.AgentInfo
	6,  // 25: argos.AgentC2.Beacon:input_type -> argos.AgentEvent
	23, // 26: argos.AgentC2.ReportFinding:input_type -> argos.Finding
	25, // 27: argos.OperatorConsole.WatchMission:input_type -> argos.MissionRequest
	27, // 28: argos.OperatorConsole.ResolveDecision:input_type -> argos.DecisionResponse
	29, // 29: argos.OperatorConsole.SetMode:input_type -> argos.ModeChange
	31, // 30: argos.OperatorConsole.ExecuteCommand:input_type -> argos.ManualCommand
	33, // 31: argos.OperatorConsole.GetWorldGraph:input_type -> argos.WorldGraphRequest
	5,  // 32: argos.AgentC2.Register:output_type -> argos.RegisterAck
	14, // 33: argos.AgentC2.Beacon:output_type -> argos.DirectorCommand
	24, // 34: argos.AgentC2.ReportFinding:output_type -> argos.FindingAck
	26, // 35: argos.OperatorConsole.WatchMission:output_type -> argos.MissionUpdate
	28, // 36: argos.OperatorConsole.ResolveDecision:output_type -> argos.DecisionAck
	30, // 37: argos.OperatorConsole.SetMode:output_type -> argos.ModeAck
	32, // 38: argos.OperatorConsole.ExecuteCommand:output_type -> argos.CommandResult
	34, // 39: argos.OperatorConsole.GetWorldGraph:output_type -> argos.WorldGraphSnapshot
	32, // [32:40] is the sub-list for method output_type
	24, // [24:32] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_argos_proto_init() }
func file_argos_proto_init() {
	if File_argos_proto != nil {
		return
	}
	file_argos_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentEvent_Scan)(nil),
		(*AgentEvent_Exploit)(nil),
		(*AgentEvent_Cred)(nil),
		(*AgentEvent_Flag)(nil),
		(*AgentEvent_Defense)(nil),
		(*AgentEvent_Hb)(nil),
	}
	file_argos_proto_msgTypes[10].OneofWrappers = []any{
		(*DirectorCommand_ScanCmd)(nil),
		(*DirectorCommand_ExploitCmd)(nil),
		(*DirectorCommand_PersistCmd)(nil),
		(*DirectorCommand_ExfilCmd)(nil),
		(*DirectorCommand_PivotCmd)(nil),
		(*DirectorCommand_CleanupCmd)(nil),
		(*DirectorCommand_DeployCmd)(nil),
		(*DirectorCommand_SleepCmd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argos_proto_rawDesc), len(file_argos_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_argos_proto_goTypes,
		DependencyIndexes: file_argos_proto_depIdxs,
		EnumInfos:         file_argos_proto_enumTypes,
		MessageInfos:      file_argos_proto_msgTypes,
	}.Build()
	File_argos_proto = out.File
	file_argos_proto_goTypes = nil
	file_argos_proto_depIdxs = nil
}
