// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.1
// source: argos.proto

package argospb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentC2_Register_FullMethodName      = "/argos.AgentC2/Register"
	AgentC2_Beacon_FullMethodName        = "/argos.AgentC2/Beacon"
	AgentC2_ReportFinding_FullMethodName = "/argos.AgentC2/ReportFinding"
)

// AgentC2Client is the client API for AgentC2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentC2Client interface {
	Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*RegisterAck, error)
	Beacon(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, DirectorCommand], error)
	ReportFinding(ctx context.Context, in *Finding, opts ...grpc.CallOption) (*FindingAck, error)
}

type agentC2Client struct {
	cc grpc.ClientConnInterface
}

func NewAgentC2Client(cc grpc.ClientConnInterface) AgentC2Client {
	return &agentC2Client{cc}
}

func (c *agentC2Client) Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*RegisterAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAck)
	err := c.cc.Invoke(ctx, AgentC2_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentC2Client) Beacon(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, DirectorCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentC2_ServiceDesc.Streams[0], AgentC2_Beacon_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentEvent, DirectorCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentC2_BeaconClient = grpc.BidiStreamingClient[AgentEvent, DirectorCommand]

func (c *agentC2Client) ReportFinding(ctx context.Context, in *Finding, opts ...grpc.CallOption) (*FindingAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindingAck)
	err := c.cc.Invoke(ctx, AgentC2_ReportFinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentC2Server is the server API for AgentC2 service.
// All implementations must embed UnimplementedAgentC2Server
// for forward compatibility.
type AgentC2Server interface {
	Register(context.Context, *AgentInfo) (*RegisterAck, error)
	Beacon(grpc.BidiStreamingServer[AgentEvent, DirectorCommand]) error
	ReportFinding(context.Context, *Finding) (*FindingAck, error)
	mustEmbedUnimplementedAgentC2Server()
}

// UnimplementedAgentC2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentC2Server struct{}

func (UnimplementedAgentC2Server) Register(context.Context, *AgentInfo) (*RegisterAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentC2Server) Beacon(grpc.BidiStreamingServer[AgentEvent, DirectorCommand]) error {
	return status.Error(codes.Unimplemented, "method Beacon not implemented")
}
func (UnimplementedAgentC2Server) ReportFinding(context.Context, *Finding) (*FindingAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportFinding not implemented")
}
func (UnimplementedAgentC2Server) mustEmbedUnimplementedAgentC2Server() {}
func (UnimplementedAgentC2Server) testEmbeddedByValue()                 {}

// UnsafeAgentC2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentC2Server will
// result in compilation errors.
type UnsafeAgentC2Server interface {
	mustEmbedUnimplementedAgentC2Server()
}

func RegisterAgentC2Server(s grpc.ServiceRegistrar, srv AgentC2Server) {
	// If the following call panics, it indicates UnimplementedAgentC2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentC2_ServiceDesc, srv)
}

func _AgentC2_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentC2Server).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentC2_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentC2Server).Register(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentC2_Beacon_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentC2Server).Beacon(&grpc.GenericServerStream[AgentEvent, DirectorCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentC2_BeaconServer = grpc.BidiStreamingServer[AgentEvent, DirectorCommand]

func _AgentC2_ReportFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Finding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentC2Server).ReportFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentC2_ReportFinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentC2Server).ReportFinding(ctx, req.(*Finding))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentC2_ServiceDesc is the grpc.ServiceDesc for AgentC2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentC2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argos.AgentC2",
	HandlerType: (*AgentC2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentC2_Register_Handler,
		},
		{
			MethodName: "ReportFinding",
			Handler:    _AgentC2_ReportFinding_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Beacon",
			Handler:       _AgentC2_Beacon_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "argos.proto",
}

const (
	OperatorConsole_WatchMission_FullMethodName    = "/argos.OperatorConsole/WatchMission"
	OperatorConsole_ResolveDecision_FullMethodName = "/argos.OperatorConsole/ResolveDecision"
	OperatorConsole_SetMode_FullMethodName         = "/argos.OperatorConsole/SetMode"
	OperatorConsole_ExecuteCommand_FullMethodName  = "/argos.OperatorConsole/ExecuteCommand"
	OperatorConsole_GetWorldGraph_FullMethodName   = "/argos.OperatorConsole/GetWorldGraph"
)

// OperatorConsoleClient is the client API for OperatorConsole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperatorConsoleClient interface {
	WatchMission(ctx context.Context, in *MissionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MissionUpdate], error)
	ResolveDecision(ctx context.Context, in *DecisionResponse, opts ...grpc.CallOption) (*DecisionAck, error)
	SetMode(ctx context.Context, in *ModeChange, opts ...grpc.CallOption) (*ModeAck, error)
	ExecuteCommand(ctx context.Context, in *ManualCommand, opts ...grpc.CallOption) (*CommandResult, error)
	GetWorldGraph(ctx context.Context, in *WorldGraphRequest, opts ...grpc.CallOption) (*WorldGraphSnapshot, error)
}

type operatorConsoleClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorConsoleClient(cc grpc.ClientConnInterface) OperatorConsoleClient {
	return &operatorConsoleClient{cc}
}

func (c *operatorConsoleClient) WatchMission(ctx context.Context, in *MissionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MissionUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OperatorConsole_ServiceDesc.Streams[0], OperatorConsole_WatchMission_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MissionRequest, MissionUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorConsole_WatchMissionClient = grpc.ServerStreamingClient[MissionUpdate]

func (c *operatorConsoleClient) ResolveDecision(ctx context.Context, in *DecisionResponse, opts ...grpc.CallOption) (*DecisionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionAck)
	err := c.cc.Invoke(ctx, OperatorConsole_ResolveDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) SetMode(ctx context.Context, in *ModeChange, opts ...grpc.CallOption) (*ModeAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModeAck)
	err := c.cc.Invoke(ctx, OperatorConsole_SetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) ExecuteCommand(ctx context.Context, in *ManualCommand, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, OperatorConsole_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) GetWorldGraph(ctx context.Context, in *WorldGraphRequest, opts ...grpc.CallOption) (*WorldGraphSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorldGraphSnapshot)
	err := c.cc.Invoke(ctx, OperatorConsole_GetWorldGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorConsoleServer is the server API for OperatorConsole service.
// All implementations must embed UnimplementedOperatorConsoleServer
// for forward compatibility.
type OperatorConsoleServer interface {
	WatchMission(*MissionRequest, grpc.ServerStreamingServer[MissionUpdate]) error
	ResolveDecision(context.Context, *DecisionResponse) (*DecisionAck, error)
	SetMode(context.Context, *ModeChange) (*ModeAck, error)
	ExecuteCommand(context.Context, *ManualCommand) (*CommandResult, error)
	GetWorldGraph(context.Context, *WorldGraphRequest) (*WorldGraphSnapshot, error)
	mustEmbedUnimplementedOperatorConsoleServer()
}

// UnimplementedOperatorConsoleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperatorConsoleServer struct{}

func (UnimplementedOperatorConsoleServer) WatchMission(*MissionRequest, grpc.ServerStreamingServer[MissionUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchMission not implemented")
}
func (UnimplementedOperatorConsoleServer) ResolveDecision(context.Context, *DecisionResponse) (*DecisionAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveDecision not implemented")
}
func (UnimplementedOperatorConsoleServer) SetMode(context.Context, *ModeChange) (*ModeAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMode not implemented")
}
func (UnimplementedOperatorConsoleServer) ExecuteCommand(context.Context, *ManualCommand) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedOperatorConsoleServer) GetWorldGraph(context.Context, *WorldGraphRequest) (*WorldGraphSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorldGraph not implemented")
}
func (UnimplementedOperatorConsoleServer) mustEmbedUnimplementedOperatorConsoleServer() {}
func (UnimplementedOperatorConsoleServer) testEmbeddedByValue()                         {}

// UnsafeOperatorConsoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorConsoleServer will
// result in compilation errors.
type UnsafeOperatorConsoleServer interface {
	mustEmbedUnimplementedOperatorConsoleServer()
}

func RegisterOperatorConsoleServer(s grpc.ServiceRegistrar, srv OperatorConsoleServer) {
	// If the following call panics, it indicates UnimplementedOperatorConsoleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperatorConsole_ServiceDesc, srv)
}

func _OperatorConsole_WatchMission_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MissionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OperatorConsoleServer).WatchMission(m, &grpc.GenericServerStream[MissionRequest, MissionUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorConsole_WatchMissionServer = grpc.ServerStreamingServer[MissionUpdate]

func _OperatorConsole_ResolveDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).ResolveDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_ResolveDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).ResolveDecision(ctx, req.(*DecisionResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_SetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).SetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_SetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).SetMode(ctx, req.(*ModeChange))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManualCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).ExecuteCommand(ctx, req.(*ManualCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_GetWorldGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorldGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).GetWorldGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_GetWorldGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).GetWorldGraph(ctx, req.(*WorldGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperatorConsole_ServiceDesc is the grpc.ServiceDesc for OperatorConsole service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatorConsole_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argos.OperatorConsole",
	HandlerType: (*OperatorConsoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveDecision",
			Handler:    _OperatorConsole_ResolveDecision_Handler,
		},
		{
			MethodName: "SetMode",
			Handler:    _OperatorConsole_SetMode_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _OperatorConsole_ExecuteCommand_Handler,
		},
		{
			MethodName: "GetWorldGraph",
			Handler:    _OperatorConsole_GetWorldGraph_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchMission",
			Handler:       _OperatorConsole_WatchMission_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "argos.proto",
}
